export const usersConstants = {
  GET_ALL_REQUEST: 'GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE',
  
  // UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  // UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  // UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  // CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  // CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  // CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  // DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  // DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  // DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
};
